-- MySQL Script generated by MySQL Workbench
-- Mon Dec  2 16:47:50 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`administrador` (
  `matricula` INT NOT NULL,
  `senha` VARCHAR(15) NOT NULL,
  `numero` INT NULL DEFAULT NULL,
  `complemento` VARCHAR(20) NULL DEFAULT NULL,
  `cidade` VARCHAR(20) NULL DEFAULT NULL,
  `bairro` VARCHAR(20) NULL DEFAULT NULL,
  `rua` VARCHAR(50) NULL DEFAULT NULL,
  `cep` VARCHAR(15) NULL DEFAULT NULL,
  `estado` VARCHAR(2) NULL DEFAULT NULL,
  `dataVinculo` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`matricula`));


-- -----------------------------------------------------
-- Table `mydb`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professor` (
  `titulacao` VARCHAR(50) NULL DEFAULT NULL,
  `matricula` INT NOT NULL,
  `senha` VARCHAR(15) NOT NULL,
  `complemento` VARCHAR(20) NULL DEFAULT NULL,
  `cidade` VARCHAR(20) NULL DEFAULT NULL,
  `bairro` VARCHAR(20) NULL DEFAULT NULL,
  `rua` VARCHAR(50) NULL DEFAULT NULL,
  `cep` VARCHAR(15) NULL DEFAULT NULL,
  `estado` VARCHAR(2) NULL DEFAULT NULL,
  `dataVinculo` DATETIME NOT NULL,
  PRIMARY KEY (`matricula`));


-- -----------------------------------------------------
-- Table `mydb`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`curso` (
  `nome` VARCHAR(30) NOT NULL,
  `idCurso` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idCurso`));


-- -----------------------------------------------------
-- Table `mydb`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turma` (
  `idTurma` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `ano` INT NOT NULL,
  `semestre` INT NOT NULL,
  `idCurso` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idTurma`),
  INDEX (`idCurso` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`idCurso`)
    REFERENCES `mydb`.`curso` (`idCurso`));


-- -----------------------------------------------------
-- Table `mydb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno` (
  `dataVinculo` DATETIME NOT NULL,
  `matricula` INT NOT NULL,
  `senha` VARCHAR(15) NOT NULL,
  `complemento` VARCHAR(20) NULL DEFAULT NULL,
  `cidade` VARCHAR(20) NULL DEFAULT NULL,
  `bairro` VARCHAR(20) NULL DEFAULT NULL,
  `rua` VARCHAR(50) NULL DEFAULT NULL,
  `cep` VARCHAR(15) NULL DEFAULT NULL,
  `estado` VARCHAR(2) NULL DEFAULT NULL,
  `idTurma` INT NULL DEFAULT NULL,
  `nome` VARCHAR(30) NULL,
  PRIMARY KEY (`matricula`),
  INDEX (`idTurma` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`idTurma`)
    REFERENCES `mydb`.`turma` (`idTurma`));


-- -----------------------------------------------------
-- Table `mydb`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disciplina` (
  `nome` VARCHAR(25) NOT NULL,
  `idDisciplina` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `area` VARCHAR(20) NOT NULL,
  `idProfessor` INT NULL DEFAULT NULL,
  `periodo` VARCHAR(20) NOT NULL,
  `turma_idTurma` INT NOT NULL,
  PRIMARY KEY (`idDisciplina`),
  INDEX (`idProfessor` ASC) VISIBLE,
  INDEX `fk_disciplina_turma1_idx` (`turma_idTurma` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`idProfessor`)
    REFERENCES `mydb`.`professor` (`matricula`),
  CONSTRAINT `fk_disciplina_turma1`
    FOREIGN KEY (`turma_idTurma`)
    REFERENCES `mydb`.`turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nota` (
  `nota` DECIMAL(4) NOT NULL,
  `idNota` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `tipo` INT NOT NULL,
  `disciplina_idDisciplina` INT NOT NULL,
  PRIMARY KEY (`idNota`),
  INDEX `fk_nota_disciplina1_idx` (`disciplina_idDisciplina` ASC) VISIBLE,
  CONSTRAINT `fk_nota_disciplina1`
    FOREIGN KEY (`disciplina_idDisciplina`)
    REFERENCES `mydb`.`disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
